### ISSUE TITLE
High Level Subjects Checklist

### ISSUE THREAD

**Issue by Lokathor** [Lokathor/gba-from-scratch#3]
Here's the basics that we want to have covered so that the programmer can utilize all the primary features of the GBA.

Currently there's no particular ordering to this list.

* [ ] Keypad
* [ ] Timers
* [ ] DMA
* [ ] Text Mode Backgrounds
* [ ] Affine Mode Backgrounds
* [ ] Bitmap Mode Backgrounds
* [ ] Graphic Special Effects
* [ ] Interrupts
* [ ] Fixed Point Math
* [ ] Save RAM
* [ ] Generated Sound
* [ ] FIFO Sound
* [ ] Assembly
